//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdvSearch
    {
        public System.Guid AdvSearchID { get; set; }
        public string DomainName { get; set; }
        public string DomainLink { get; set; }
        public Nullable<int> Age { get; set; }
        public Nullable<int> PageRank { get; set; }
        public Nullable<int> MOZDA { get; set; }
        public Nullable<int> MOZPA { get; set; }
        public Nullable<decimal> MozRank { get; set; }
        public Nullable<decimal> MozTrust { get; set; }
        public Nullable<int> CF { get; set; }
        public Nullable<int> TF { get; set; }
        public Nullable<decimal> AlexARank { get; set; }
        public Nullable<int> MozDom { get; set; }
        public Nullable<int> MajDom { get; set; }
        public string SimilarWeb { get; set; }
        public string SemTarf { get; set; }
        public Nullable<int> DomainPrice { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public Nullable<System.DateTime> EsitmateEnd { get; set; }
        public System.Guid UserID { get; set; }
        public string Ref { get; set; }
        public bool IsAuction { get; set; }
        public bool IsGOdaddy { get; set; }
    }
}
