//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuctionHistory
    {
        public System.Guid HistoryID { get; set; }
        public string Text { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.Guid AuctionLink { get; set; }
    }
}
