//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class BackOrders
    {
        public System.Guid OrderID { get; set; }
        public string DomainName { get; set; }
        public string AlertEmail1 { get; set; }
        public string AlertEmail2 { get; set; }
        public System.DateTime DateToOrder { get; set; }
        public int CreditsToUse { get; set; }
        public bool Private { get; set; }
        public System.Guid GoDaddyAccount { get; set; }
        public bool Processed { get; set; }
    
        public virtual GoDaddyAccount GoDaddyAccount1 { get; set; }
    }
}
