//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chart_AuctionHistory
    {
        public string Username { get; set; }
        public Nullable<int> TotalAuctions { get; set; }
        public Nullable<int> AuctionsThisMonth { get; set; }
        public Nullable<int> AuctionsWonTotal { get; set; }
    }
}
