//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class GoDaddyAccount
    {
        public GoDaddyAccount()
        {
            this.Auctions = new HashSet<Auctions>();
            this.AuctionSearch = new HashSet<AuctionSearch>();
        }
    
        public System.Guid AccountID { get; set; }
        public string GoDaddyUsername { get; set; }
        public string GoDaddyPassword { get; set; }
        public System.Guid UserID { get; set; }
        public bool Verified { get; set; }
    
        public virtual Users Users { get; set; }
        public virtual ICollection<Auctions> Auctions { get; set; }
        public virtual ICollection<AuctionSearch> AuctionSearch { get; set; }
    }
}
