//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASEntityFramework
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class ASEntities : DbContext
    {
        public ASEntities()
            : base("name=ASEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<GoDaddyAccount> GoDaddyAccount { get; set; }
        public DbSet<Users> Users { get; set; }
        public DbSet<Auctions> Auctions { get; set; }
        public DbSet<AuctionSearch> AuctionSearch { get; set; }
        public DbSet<AuctionHistory> AuctionHistory { get; set; }
        public DbSet<AuctionHistoryView> AuctionHistoryView { get; set; }
        public DbSet<Alerts> Alerts { get; set; }
        public DbSet<EventLog> EventLog { get; set; }
        public DbSet<SearchTable> SearchTable { get; set; }
        public DbSet<SearchLayout> SearchLayout { get; set; }
        public DbSet<AdvSearch> AdvSearch { get; set; }
        public DbSet<SearchConfig> SearchConfig { get; set; }
        public DbSet<SystemConfig> SystemConfig { get; set; }
        public DbSet<Chart_AuctionHistory> Chart_AuctionHistory { get; set; }
        public DbSet<Chart_AuctionsEnding> Chart_AuctionsEnding { get; set; }
        public DbSet<Chart_PopularDomainsThisMonth> Chart_PopularDomainsThisMonth { get; set; }
    
        public virtual int USP_SearchQueryBuilder2(string userID)
        {
            var userIDParameter = userID != null ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("USP_SearchQueryBuilder2", userIDParameter);
        }
    }
}
