//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class SearchTable
    {
        public System.Guid ID { get; set; }
        public string SearchValue { get; set; }
        public string FieldName { get; set; }
        public string Value { get; set; }
        public System.Guid UserID { get; set; }
        public string DataType { get; set; }
        public int ItemOrder { get; set; }
    }
}
