//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public Users()
        {
            this.GoDaddyAccount = new HashSet<GoDaddyAccount>();
        }
    
        public System.Guid UserID { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public bool ReceiveEmails { get; set; }
        public int AccessLevel { get; set; }
    
        public virtual ICollection<GoDaddyAccount> GoDaddyAccount { get; set; }
    }
}
